SPRING:
  PROFILES:
    ACTIVE:
      dev
---
spring:
  config:
    activate:
      on-profile: dev

database:
  url: jdbc:postgresql://localhost:5432/MrktData
  username: hetroboomin
  password: F1JckC0V1D$
  driver: org.postgresql.Driver

---
spring:
  config:
    activate:
      on-profile: server

database:
  url: jdbc:postgresql://192.168.1.21:16666/mrktdata
  username: publicapi
  password: jenny
  driver: org.postgresql.Driver